CREATE DATABASE car_db;

\c car_db

CREATE TABLE IF NOT EXISTS car
(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    car_name VARCHAR,
    brand VARCHAR,
    country VARCHAR,
    price NUMERIC,
    quantity INTEGER
);